Added GetLatestQuote (/intraday/latest)
orshe4/marketstack pull request #3
Opened 2020-09-18 05:49 UTC by Jenscaasen

2020-09-18 08:13 UTC, orshe4 commented
Please fix conflicts so I could merge

2020-09-18 08:40 UTC, Jenscaasen commented
Sorry for the conflicts, i am completely new to open source and github and pull requests. Should be solved now.

2020-09-18 12:04 UTC, orshe4 requested changes

2020-09-18 12:04 UTC, orshe4 commented on Marketstack/Services/MarketstackService.cs
> +            return _httpClient.GetSingleAsync<StockBar>($"http://api.marketstack.com/v1/intraday/latest?symbols={stockSymbol}", _options.ApiToken, _throttled);
Change it to:
`return _httpClient.GetAsync<StockBar>($"http://api.marketstack.com/v1/intraday/latest?symbols={stockSymbol}", _options.ApiToken, _throttled).FirstAsync();`

2020-09-18 12:04 UTC, orshe4 commented on Marketstack/Services/HttpClientExtensions.cs
> +        public static async Task<T> GetSingleAsync<T>(this HttpClient httpClient, string url, string apiToken, Throttled throttled)
I think that this function is not necessary

2020-09-18 12:04 UTC, orshe4 commented on Marketstack.Tests/MarketstackServiceTests.cs
> +        public async Task GetLatestQuote_ReturnsBars()
Rename to `GetLatestQuote_ReturnsBar`

2020-09-18 12:04 UTC, orshe4 commented on Marketstack.Tests/MarketstackServiceTests.cs
> +            Assert.NotNull(bar);
You can add some assertions to the bar date. Validate that it is the latest bar.

2020-09-18 12:12 UTC, orshe4 requested changes

2020-09-18 12:12 UTC, orshe4 commented on Marketstack/Services/MarketstackService.cs
> +            return _httpClient.GetSingleAsync<StockBar>($"http://api.marketstack.com/v1/intraday/latest?symbols={stockSymbol}", _options.ApiToken, _throttled);
Please use the following api endpoints:

`/tickers/[symbol]/eod/latest` | Obtain the latest end-of-day data for a given stock symbol. 

`/tickers/[symbol]/intraday/latest` | Obtain the latest intraday data for a given stock symbol

2020-09-20 13:09 UTC, orshe4 commented
> Sorry for the conflicts. I am completely new to open source and GitHub and pull requests. Should be solved now.

I finished the review. Please review my comments. Thanks again for contributing to my repo.

2020-09-30 21:45 UTC, orshe4 commented
Closed due to inactivity. In case you would like to continue with this merge, please pulled from the master and review my comments.

Please note the API changes in `IMarketstackService.cs`

2020-09-30 21:45 UTC, closed without merging